### PR TITLE
changes saved

### PR DESCRIPTION
**Pull request by mmmim24**

### CODE REVIEW

**Comment by arafat-hasan** [comment]
Since this is a list of Bangladeshi tech companies, I don't think it would be reasonable to include remote foreign companies here. Is there any office of _Widespace_, _Kinetik Care_, or _LifeData_ in Bangladesh?

**Comment by mmmim24** [comment]
Widespace was previously included, I dont know anything about that
Lifedata and kinetic care has a good number of bangladeshi employees. So I wanted to include them as some of SUST alumni are in there

**Comment by arafat-hasan** [comment]
> Widespace was previously included, I dont know anything about that
> Lifedata and kinetic care has a good number of bangladeshi employees. So I wanted to include them as some of SUST alumni are in there


Even after that, I don’t think it would be right to add these companies. Many Bangladeshis also work on Crossover, so I don't think it would be right to add that.

IMHO, whether the company works remotely or in its own office, it is necessary to see whether the company has an office in Bangladesh.

However, we also need to take into account the views of others. 


@mmahmoodictbd Bhai, if you look at this matter a little.

**Comment by mmahmoodictbd** [comment]
Thanks, @mmmim24 for the PR. 

It's not about the `remote` part, a company can be remote and part of this list. Question is - is it **registered** in Bangladesh? If the answer is `yes`, then it should be included.



Are they (`Kinetik Care` and `LifeData`) registered in Bangladesh?

**Comment by mmmim24** [comment]
I get to know that kinetik care is registered but not sure about life data. You can check the linkedIn page of them for more details.

**Comment by mmmim24** [comment]
Now I removed LifeData and Kinetik.Care and two more companies

**Pull request merged**
