### PR TITLE
Create tech-companies-of-bangladesh

### PR DESCRIPTION
**Pull request by alsakib748**
tech-companies-of-bangladesh-details

### CODE REVIEW

**Comment by alsakib748** [comment]
tech-companies-of-bangladesh-details

**Comment by alsakib748** [comment]
all-tech-companies-of-bangladesh

**Comment by alsakib748** [comment]
this is details of all bangladeshi tech company

**Review by arafat-hasan — COMMENTED** [review]
This PR is unclear to me. @alsakib748, Could you please explain why we need this new file, which is currently blank?

I am rejecting this PR for now. If you have a strong plan, please explain it in your PR or create an issue for discussion. Once we reach an agreement, we can proceed with merging the PRs.

**Pull request closed without merging**
